import { createApplicationIntakeService, createDecisionService, createDeepAnalysisService, createInterviewResultService, createResumeAnalysisService, createSchedulingService } from "@interviehire/domain-hiring";
import { connectHiringDatabase, DrizzleAnalysisRefRepository, DrizzleApplicationIntakeRepository, DrizzleApplicationRepository, DrizzleDecisionRepository, DrizzleInterviewResultRepository, DrizzleResumeAnalysisRepository, DrizzleScheduleRepository, migrateHiringDatabase } from "@interviehire/db-hiring";
import { createCoreApp } from "./app"; import { createLegacyGateway } from "./compatibility"; import { createHttpInterviewEvaluationClient, createHttpInterviewProvisioner } from "./interview-client";
const databaseUrl = process.env.DATABASE_URL; if (!databaseUrl) throw new Error("DATABASE_URL is required");
if (process.env.RUN_MIGRATIONS === "true") await migrateHiringDatabase(databaseUrl);
const connection = connectHiringDatabase(databaseUrl); const interviewBaseUrl = process.env.INTERVIEW_API_URL ?? "http://127.0.0.1:4200"; const secret = process.env.INTERNAL_SERVICE_SECRET ?? "dev-internal-secret";
const interview = createHttpInterviewProvisioner({ baseUrl: interviewBaseUrl, internalSecret: secret }); const evaluation = createHttpInterviewEvaluationClient({ baseUrl: interviewBaseUrl, internalSecret: secret }); const applications = new DrizzleApplicationRepository(connection.db);
const app = createCoreApp({ applicationRepository: applications, applicationQueries: applications, intake: createApplicationIntakeService(new DrizzleApplicationIntakeRepository(connection.db), () => `app_${crypto.randomUUID()}`, () => new Date().toISOString()), resumeAnalysis: createResumeAnalysisService(new DrizzleResumeAnalysisRepository(connection.db), { newId: () => `resume_${crypto.randomUUID()}`, now: () => new Date().toISOString() }), scheduling: createSchedulingService(new DrizzleScheduleRepository(connection.db), interview, () => new Date().toISOString()), decisions: createDecisionService(new DrizzleDecisionRepository(connection.db), () => new Date().toISOString()), deepAnalysis: createDeepAnalysisService(new DrizzleAnalysisRefRepository(connection.db), evaluation), interviewResults: createInterviewResultService(new DrizzleInterviewResultRepository(connection.db)), internalServiceSecret: secret, ...(process.env.LEGACY_API_URL ? { legacyGateway: createLegacyGateway({ baseUrl: process.env.LEGACY_API_URL }) } : {}) });
app.listen(Number(process.env.PORT ?? 4100)); console.log(`Core API listening on ${app.server?.url}`);
